Ext.define('Appmob.appmob.shared.com.model.appbasicsetup.usermanagement.UserDetailModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "userId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "userAccessCode",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "useraccesslevelid",
          "reference": "UserAccessLevel",
          "defaultValue": ""
     }, {
          "name": "userAccessLevelUserAccessLevelName",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "useraccessdomainid",
          "reference": "UserAccessDomain",
          "defaultValue": ""
     }, {
          "name": "userAccessDomainUserAccessDomainName",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "multiFactorAuthEnabled",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "genTempOneTimeAuth",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "allowMultipleLogin",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "isLocked",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "isDeleted",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "changeAuthNextLogin",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "authExpiryDate",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "authAlgo",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "lastAuthChangeDate",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "sessionTimeout",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "UserData",
          "reference": "UserDataModel"
     }, {
          "name": "PassRecovery",
          "reference": "PassRecoveryModel"
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});